# This entire file has been commented out and moved to Resources/Prototypes/_WF/Entities/Objects/Specific/Outlaw/wanted_outlaw.yml.
# We still want to use some of the old pirate entity IDs on the backend so we don't have to change crazy amounts of references in the code.
# If there's a conflict here, we need to look at if it *shouldn't* be ported over because it probably doesn't fit with our antag structure.

# - type: job
#   id: NFPirateCaptain
#   name: job-name-nf-pirate-captain
#   description: job-description-nf-pirate-captain
#   playTimeTracker: JobPirateCaptain
#   whitelisted: true
#   requirements:
#     - !type:OverallPlaytimeRequirement
#       time: 388800 # 48 hours
#   startingGear: NFPirateCaptainGear
#   alwaysUseSpawner: true
#   hideConsoleVisibility: true
#   canBeAntag: true
#   icon: "JobIconNFPirateCaptain"
#   supervisors: job-supervisors-freebooters-union
#   weight: 40
#   displayWeight: 40
#   setPreference: false
#   newPlayerMessage: false
#   access:
#   - Pirate
#   accessGroups:
#   - GeneralAccess
#   special:
#   - !type:AddComponentSpecial
#     components:
#     - type: AutoPirateCaptain
#     - type: SpecialSectorStationRecord # must be given on spawn
#       recordGeneration: FalseRecord
#     - type: DisableSuitSensors
#   - !type:AddImplantSpecial
#     implants: [ FreelanceTrackingImplant ]
#   - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
#     holiday: FrontierBirthday
#     prototype: FrontierBirthdayGift

# - type: startingGear
#   id: NFPirateCaptainGear
#   equipment:
#     belt: ClothingBeltUtility
#     pocket1: BasePirateUplinkRadioPirateCaptain
#     pocket2: EnergyCutlass
#   storage:
#     back:
#     - AppraisalTool
#     - PirateTechFabFlatpack
#     - Multitool

# - type: chameleonOutfit
#   id: NFPirateCaptainChameleonOutfit
#   job: NFPirateCaptain
