contact_links:
  - name: Report a Security Vulnerability
    url: https://github.com/space-wizards/space-station-14/blob/master/SECURITY.md
    about: Please report security vulnerabilities privately so we can fix them before they are publicly disclosed. Redirects to SS14's vulnerability page.
  - name: Request a Feature
    url: https://discord.gg/QpVfma2eAp
    about: Submit feature requests on Wayfarer's Discord server (https://discord.gg/QpVfma2eAp).
